### ISSUE TITLE
train my caffemodel error

### ISSUE THREAD

**Issue by gzz1529657064** [jkjung-avt/tensorrt_demos#11]
I want to train MobileNet-YOLOv3 caffemodel so that I can transplant it on TX2.
But when I use MobileNet-YOLOv3 to train my dataset, error occurred.

Opened lmdb /home/gzz/data/VOCdevkit/MyDataSet/lmdb/MyDataSet_trainval_lmdb/
I1018 09:27:19.771530 17056 annotated_data_layer.cpp:78] output data size: 4,3,608,608
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.YoloSegLabel: 4:15: Message type "caffe.YoloSegItem" has no field named "display_name".
F1018 09:27:19.771678 17056 annotated_data_layer.cpp:134] Check failed: ReadProtoFromTextFile(label_map_file_, &label_map_) Failed to read label map file.

How should I do?

**Comment by jkjung-avt** [comment]
I think the error message says:

* "YoloSegLabel" expects image segmentation labels in the defined format, reference: https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/proto/caffe.proto#L70
* However, in your train.prototxt, you incorrectly specified a "labelmap_xxx.prototxt" (for object detection, not segmentation).

I'm closing this issue since it's not relevant to this tensorrt_demos repository...
