### ISSUE TITLE
Retnet50 to UFF

### ISSUE THREAD

**Issue by PatrikPatrik2** [jkjung-avt/tensorrt_demos#123]
Is it not possible to convert Retnet50 frozen graph to UFF using build_enginge? When I try i get an error

`2020-05-30 09:25:09.889223: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "build_engine_2.py", line 219, in <module>
    main()
  File "build_engine_2.py", line 196, in main
    spec)
  File "build_engine_2.py", line 172, in add_plugin
    graph.find_nodes_by_op("NMS_TRT")[0].input.remove("Input")
ValueError: remove(x): x not in container
`

**Comment by jkjung-avt** [comment]
Please note that [ssd/build_engine.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py) is designed to handle tensorflow SSD models only.  It would not handle classifier models correctly.

Otherwise, if you are referring to "ssd_resnet_50_fpn_coco" ("RetinaNet"), please check out https://github.com/jkjung-avt/tensorrt_demos/issues/40.  Other people are also having problems with it.
