### ISSUE TITLE
Suggestion rtsp output

### ISSUE THREAD

**Issue by tomcatxx** [jkjung-avt/tensorrt_demos#209]
Hi, first thanks for all the nice examples. Helped me a lot.
Im playing around with object detection in front of an cctv system to trigger alerts.
Would it be possible to get an rtsp stream output? 
I would use deepstream but wasnt able to get yolo4 running.

**Comment by jkjung-avt** [comment]
Thanks for the suggestion.  I might look into that when I have time, but no promise.

**Comment by tomcatxx** [comment]
nice ty 👍

**Comment by jkjung-avt** [comment]
I created a MJPEG sample.  You could run it and view detection results remotely using a web browser.  Please check https://github.com/jkjung-avt/tensorrt_demos/issues/226#issuecomment-691689456.

I don't plan to develop RTSP streaming code since it probably depends heavily on gstreamer and the underlying libraries.  I think you could adapt the MJPEG sample code to achieve that.

**Comment by tomcatxx** [comment]
Ty very much. For monitoring the detections it fits my needs. I will test it next days.
For full 4K stream opencv needs anyways to much CPU so I just detect with FullHD and record the 4k stream with Zoneminder if detections happens.
