### ISSUE TITLE
delay and  Utilization

### ISSUE THREAD

**Issue by Shame-fight** [jkjung-avt/tensorrt_demos#210]
Thank you again for your work, I have two concerns:
1. yolov4_trt can reach 4-5fps on nano, is there a delay? darknet_yolo has some delay on nano, so I have this question.
2.How much is the utilization rate of cup and gpu, because I not only need target identification, but also path planning, etc.

**Comment by jkjung-avt** [comment]
> 1. yolov4_trt can reach 4-5fps on nano, is there a delay? darknet_yolo has some delay on nano,

I used the technique described in my [Multi-threaded Camera Caffe Inferencing](https://jkjung-avt.github.io/camera-caffe-threaded/) post in order to reduce buffering time (main cause of latency) of the inferenced image frame.  You should test the code on your own target platform to see if that meets your requirement.

> 2.How much is the utilization rate of cup and gpu

As I recall, on Jetson Nano, GPU utilization is close to 99% and CPU ~20%.  Again, you should do your own testing...
