### ISSUE TITLE
Dynamic Batch Sizes

### ISSUE THREAD

**Issue by skyler1253** [jkjung-avt/tensorrt_demos#25]
Hi @jkjung-avt  - awesome work with this repo.  I think this is the most useful demo I've seen on the nano so far, and your work with the async function is really well done.

I'm wondering if there's an easy way to rebuild the SSD detector engines to take a batch size of (2,3,300,300), or even better to take a dynamic batch size input?

**Comment by jkjung-avt** [comment]
"Dynamic shape" support seems to be added since the very recent [TensorRT 6.0.1](https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html#tensorrt-6).  However, according to [official documentation](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes), only dynamic shapes for convolutions are supported, while input batch size still needs to be fixed when the TensorRT engine is compiled.

That being said, it's actually quite easy to modify the code to use (2, 3, 300, 300) as TRT SSD input.

1. Replace 1 with 2 in the Input Placeholder op ([link](https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py#L98))
2. Modify trt_ssd.py or trt_ssd_async.py to stack 2 input images together as a batch for inference.
