### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by hjlee9182** [jkjung-avt/tensorrt_demos#251]
![image](https://user-images.githubusercontent.com/46337218/95426635-2ddfb980-0981-11eb-8f84-29a20da72148.png)

Modify some code in 'eval_yolo.py'.

But that result FPS is lower than 'README.md' FPS. ( about 1~5FPS)

So I don't know what is problem.
Is there something wrong?

**Comment by jkjung-avt** [comment]
I measure FPS with "trt_yolo.py" directly.

You would see a lower FPS with "eval_yolo.py" because:

1. Detection confidence threshold (1e-2) is lower.  So the postprocessing (NMS) would take longer.
2. Reading various jpg files causes additional loading on the CPU and I/O.  It would slow down inference code a little bit.

**Comment by hjlee9182** [comment]
ok thank u
