### ISSUE TITLE
YOLOv4-CSP and YOLOv4x-mish are worse than YOLOv4?

### ISSUE THREAD

**Issue by GeekAlexis** [jkjung-avt/tensorrt_demos#308]
Thanks for supporting scaled YOLO. However, the performance results listed in the README don't look good for the new models. In FP16, YOLOv4-CSP-512 seems to perform even worse than YOLOv4-416, which is not consistent with the paper? Are these results expected?

**Comment by jkjung-avt** [comment]
I'm not sure.  I just took the cfg/weights published by Alexeyab's and tried to convert them into a TensorRT engine.

It might be issues of my code/implementation.  But it'd be better to verify mAP of the "yolov4-csp" cfg/weights (using darknet) really match what's on the paper first.  (I haven't done so by myself.)  After all, the authors said that [WongKinYiu/ScaledYOLOv4](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-csp), instead of darknet, is the main repository they used to produce the results on the paper.

Some additional info:  It has been reported that darknet "yolov4-csp" underperforms darknet "yolov4" on a custom dataset.

https://github.com/AlexeyAB/darknet/issues/7087#issuecomment-750107355
