### ISSUE TITLE
onnx_to_tensorrt.py  with yolov5 - int8 mode

### ISSUE THREAD

**Issue by htran170642** [jkjung-avt/tensorrt_demos#429]
Hi, I got error when using onnx_to_tensorrt.py to convert yolov5s to tensorrt.

A little modification with your code:
![image](https://user-images.githubusercontent.com/70887055/120932400-c6e8ef00-c71f-11eb-93e0-9db692ad69af.png)

 I set manually net_h, net_w = 640 and then parse yolov5s.onnx model

The error is: ERROR: INVALID_ARGUMENT: Cannot get dimensions for input: images. Input is not present in this OptimizationProfile

![image](https://user-images.githubusercontent.com/70887055/120932327-81c4bd00-c71f-11eb-9493-3e72cfbe1700.png)

 This is my model
![image](https://user-images.githubusercontent.com/70887055/120932299-6954a280-c71f-11eb-9544-b9ce5690a23a.png)

What is my problem? Thank you.
I use RTX 2080, TensorRT 7.2

**Comment by jkjung-avt** [comment]
> The error is: ERROR: INVALID_ARGUMENT: Cannot get dimensions for input: images. Input is not present in this OptimizationProfile

The input tensor of your yolov5s model seems to be "images", not "000_net" (refer to source code as shown below).  Otherwise, I have only tested my code with **DarkNet** yolo models.  I don't guarantee it to work for other frameworks without modifications.

https://github.com/jkjung-avt/tensorrt_demos/blob/bac5085d75e59369cc587cf9ec19f5120836cb3e/yolo/onnx_to_tensorrt.py#L139-L143
