### ISSUE TITLE
trt_yolo.py: Assertion `d == a + length' failed.

### ISSUE THREAD

**Issue by yusufpraditya** [jkjung-avt/tensorrt_demos#483]
I have no idea why I got this error.

python3: yolo_layer.cu:73: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion `d == a + length' failed.

Btw, I am using Jetson Nano

**Comment by jkjung-avt** [comment]
This is most likely because you've built the TensorRT engine with an older version of the code (and tried to inference with the engine using a newer version of the code).

You could fix it by:

* removing the TensorRT engine,
* rebuilding the plugin (do `make clean; make` in the "plugins" subdirectory),
* rebuilding the TensorRT engine (run "onnx_to_tensorrt.py")
